/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BajaRouteImport } from './routes/baja'
import { Route as AdminPanelRouteImport } from './routes/admin/_panel'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as PuertaListaRouteImport } from './routes/puerta/_lista'
import { Route as PuertaLoginRouteImport } from './routes/puerta/login'
import { Route as AdminPanelIndexRouteImport } from './routes/admin/_panel/index'
import { Route as AdminPanelReservasRouteImport } from './routes/admin/_panel/reservas'
import { Route as AdminPanelSuscriptoresRouteImport } from './routes/admin/_panel/suscriptores'
import { Route as PuertaListaIndexRouteImport } from './routes/puerta/_lista/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BajaRoute = BajaRouteImport.update({
  id: '/baja',
  path: '/baja',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin/_panel',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PuertaListaRoute = PuertaListaRouteImport.update({
  id: '/puerta/_lista',
  path: '/puerta',
  getParentRoute: () => rootRouteImport,
} as any)
const PuertaLoginRoute = PuertaLoginRouteImport.update({
  id: '/puerta/login',
  path: '/puerta/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelIndexRoute = AdminPanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelReservasRoute = AdminPanelReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelSuscriptoresRoute = AdminPanelSuscriptoresRouteImport.update({
  id: '/suscriptores',
  path: '/suscriptores',
  getParentRoute: () => AdminPanelRoute,
} as any)
const PuertaListaIndexRoute = PuertaListaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PuertaListaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baja': typeof BajaRoute
  '/admin': typeof AdminPanelRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/puerta': typeof PuertaListaRouteWithChildren
  '/puerta/login': typeof PuertaLoginRoute
  '/admin/reservas': typeof AdminPanelReservasRoute
  '/admin/suscriptores': typeof AdminPanelSuscriptoresRoute
  '/admin/': typeof AdminPanelIndexRoute
  '/puerta/': typeof PuertaListaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baja': typeof BajaRoute
  '/admin/login': typeof AdminLoginRoute
  '/puerta/login': typeof PuertaLoginRoute
  '/admin/reservas': typeof AdminPanelReservasRoute
  '/admin/suscriptores': typeof AdminPanelSuscriptoresRoute
  '/admin': typeof AdminPanelIndexRoute
  '/puerta': typeof PuertaListaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baja': typeof BajaRoute
  '/admin/_panel': typeof AdminPanelRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/puerta/_lista': typeof PuertaListaRouteWithChildren
  '/puerta/login': typeof PuertaLoginRoute
  '/admin/_panel/reservas': typeof AdminPanelReservasRoute
  '/admin/_panel/suscriptores': typeof AdminPanelSuscriptoresRoute
  '/admin/_panel/': typeof AdminPanelIndexRoute
  '/puerta/_lista/': typeof PuertaListaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baja'
    | '/admin'
    | '/admin/login'
    | '/puerta'
    | '/puerta/login'
    | '/admin/reservas'
    | '/admin/suscriptores'
    | '/admin/'
    | '/puerta/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/baja'
    | '/admin/login'
    | '/puerta/login'
    | '/admin/reservas'
    | '/admin/suscriptores'
    | '/admin'
    | '/puerta'
  id:
    | '__root__'
    | '/'
    | '/baja'
    | '/admin/_panel'
    | '/admin/login'
    | '/puerta/_lista'
    | '/puerta/login'
    | '/admin/_panel/reservas'
    | '/admin/_panel/suscriptores'
    | '/admin/_panel/'
    | '/puerta/_lista/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BajaRoute: typeof BajaRoute
  AdminPanelRoute: typeof AdminPanelRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  PuertaListaRoute: typeof PuertaListaRouteWithChildren
  PuertaLoginRoute: typeof PuertaLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baja': {
      id: '/baja'
      path: '/baja'
      fullPath: '/baja'
      preLoaderRoute: typeof BajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_panel': {
      id: '/admin/_panel'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puerta/_lista': {
      id: '/puerta/_lista'
      path: '/puerta'
      fullPath: '/puerta'
      preLoaderRoute: typeof PuertaListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puerta/login': {
      id: '/puerta/login'
      path: '/puerta/login'
      fullPath: '/puerta/login'
      preLoaderRoute: typeof PuertaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_panel/': {
      id: '/admin/_panel/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminPanelIndexRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/reservas': {
      id: '/admin/_panel/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminPanelReservasRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/suscriptores': {
      id: '/admin/_panel/suscriptores'
      path: '/suscriptores'
      fullPath: '/admin/suscriptores'
      preLoaderRoute: typeof AdminPanelSuscriptoresRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/puerta/_lista/': {
      id: '/puerta/_lista/'
      path: '/'
      fullPath: '/puerta/'
      preLoaderRoute: typeof PuertaListaIndexRouteImport
      parentRoute: typeof PuertaListaRoute
    }
  }
}

interface AdminPanelRouteChildren {
  AdminPanelReservasRoute: typeof AdminPanelReservasRoute
  AdminPanelSuscriptoresRoute: typeof AdminPanelSuscriptoresRoute
  AdminPanelIndexRoute: typeof AdminPanelIndexRoute
}

const AdminPanelRouteChildren: AdminPanelRouteChildren = {
  AdminPanelReservasRoute: AdminPanelReservasRoute,
  AdminPanelSuscriptoresRoute: AdminPanelSuscriptoresRoute,
  AdminPanelIndexRoute: AdminPanelIndexRoute,
}

const AdminPanelRouteWithChildren = AdminPanelRoute._addFileChildren(
  AdminPanelRouteChildren,
)

interface PuertaListaRouteChildren {
  PuertaListaIndexRoute: typeof PuertaListaIndexRoute
}

const PuertaListaRouteChildren: PuertaListaRouteChildren = {
  PuertaListaIndexRoute: PuertaListaIndexRoute,
}

const PuertaListaRouteWithChildren = PuertaListaRoute._addFileChildren(
  PuertaListaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BajaRoute: BajaRoute,
  AdminPanelRoute: AdminPanelRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  PuertaListaRoute: PuertaListaRouteWithChildren,
  PuertaLoginRoute: PuertaLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
